local M = {}

---@param c table
---@param opts table
function M.get(c, opts)
  local styles = opts.styles or {}

  return {
    -- UI
    Normal = { fg = c.fg, bg = opts.transparent and "NONE" or c.bg },
    NormalFloat = { fg = c.fg, bg = c.bg_float },
    FloatBorder = { fg = c.purple, bg = c.bg_float },
    CursorLine = { bg = c.bg_cursorline },
    CursorColumn = { bg = c.bg_cursorline },
    ColorColumn = { bg = c.bg_float },
    LineNr = { fg = c.fg_gutter },
    CursorLineNr = { fg = c.fg, bold = true },
    SignColumn = { fg = c.fg_gutter, bg = opts.transparent and "NONE" or c.bg },
    EndOfBuffer = { fg = c.bg_dark },
    VertSplit = { fg = c.bg_dark },
    WinSeparator = { fg = c.bg_dark },
    Pmenu = { fg = c.fg, bg = c.bg_float },
    PmenuSel = { fg = c.fg, bg = c.bg_cursorline, bold = true },
    PmenuSbar = { bg = c.bg_dark },
    PmenuThumb = { bg = c.purple },
    Visual = { bg = c.bg_visual },
    Search = { fg = c.bg, bg = c.yellow },
    IncSearch = { fg = c.bg, bg = c.orange, bold = true },
    MatchParen = { fg = c.yellow, bg = c.bg_cursorline, bold = true },
    StatusLine = { fg = c.fg_dim, bg = c.bg_dark },
    StatusLineNC = { fg = c.fg_gutter, bg = c.bg_dark },
    TabLine = { fg = c.fg_gutter, bg = c.bg_dark },
    TabLineSel = { fg = c.fg, bg = c.bg, bold = true },
    TabLineFill = { bg = c.bg_dark },
    Folded = { fg = c.fg_gutter, bg = c.bg_float },
    FoldColumn = { fg = c.fg_gutter, bg = opts.transparent and "NONE" or c.bg },
    NonText = { fg = c.fg_gutter },
    Whitespace = { fg = c.fg_gutter },

    -- Syntax
    Comment = { fg = c.fg_gutter, italic = styles.comments ~= false },
    Constant = { fg = c.orange },
    String = { fg = "#ff8b39" },
    Character = { fg = c.cyan },
    Number = { fg = c.orange },
    Boolean = { fg = c.orange },
    Float = { fg = c.orange },
    Identifier = { fg = c.pink },
    Function = { fg = c.cyan },
    Statement = { fg = c.yellow, bold = styles.keywords == true },
    Conditional = { fg = c.yellow },
    Repeat = { fg = c.yellow },
    Label = { fg = c.yellow },
    Operator = { fg = c.yellow },
    Keyword = { fg = c.yellow, bold = styles.keywords == true },
    Exception = { fg = c.yellow },
    PreProc = { fg = c.green },
    Include = { fg = c.green },
    Define = { fg = c.green },
    Macro = { fg = c.green },
    PreCondit = { fg = c.green },
    Type = { fg = c.red },
    StorageClass = { fg = c.yellow },
    Structure = { fg = c.red },
    Typedef = { fg = c.red },
    Special = { fg = c.cyan },
    SpecialComment = { fg = c.fg_gutter, italic = true },
    Underlined = { fg = c.pink, underline = true },
    Error = { fg = c.error },
    Todo = { fg = c.bg, bg = c.pink, bold = true },

    -- Diff
    DiffAdd = { bg = c.diff_add },
    DiffDelete = { bg = c.diff_delete },
    DiffChange = { bg = c.diff_change },
    DiffText = { bg = c.bg_cursorline, bold = true },

    -- Diagnostics
    DiagnosticError = { fg = c.error },
    DiagnosticWarn = { fg = c.warning },
    DiagnosticInfo = { fg = c.info },
    DiagnosticHint = { fg = c.hint },
    DiagnosticVirtualTextError = { fg = c.error, bg = c.bg_float },
    DiagnosticVirtualTextWarn = { fg = c.warning, bg = c.bg_float },
    DiagnosticVirtualTextInfo = { fg = c.info, bg = c.bg_float },
    DiagnosticVirtualTextHint = { fg = c.hint, bg = c.bg_float },
    DiagnosticUnderlineError = { undercurl = true, sp = c.error },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.warning },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.info },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.hint },

    -- Treesitter
    ["@comment"] = { link = "Comment" },
    ["@string"] = { link = "String" },
    ["@string.escape"] = { fg = c.cyan },
    ["@number"] = { link = "Number" },
    ["@boolean"] = { link = "Boolean" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = c.red, bold = true },
    ["@variable"] = { fg = c.pink },
    ["@variable.builtin"] = { fg = c.red, bold = true },
    ["@parameter"] = { fg = c.pink, italic = styles.parameters ~= false },
    ["@field"] = { fg = c.blue },
    ["@property"] = { fg = c.blue },
    ["@function"] = { fg = c.cyan },
    ["@function.call"] = { fg = c.cyan },
    ["@function.builtin"] = { fg = c.cyan, bold = true },
    ["@method"] = { fg = c.cyan },
    ["@keyword"] = { fg = c.yellow, bold = styles.keywords == true },
    ["@keyword.function"] = { fg = c.yellow },
    ["@keyword.return"] = { fg = c.yellow },
    ["@type"] = { fg = c.red },
    ["@type.builtin"] = { fg = c.red },
    ["@operator"] = { fg = c.yellow },
    ["@punctuation"] = { fg = c.fg_dim },
    ["@tag"] = { fg = c.green },
    ["@tag.attribute"] = { fg = c.yellow },
    ["@constructor"] = { fg = c.red },

    -- LSP semantic
    ["@lsp.type.comment"] = { link = "Comment" },
    ["@lsp.type.function"] = { link = "Function" },
    ["@lsp.type.method"] = { link = "Function" },
    ["@lsp.type.property"] = { fg = c.blue },
    ["@lsp.type.variable"] = { fg = c.pink },
    ["@lsp.type.parameter"] = { fg = c.pink, italic = styles.parameters ~= false },
    ["@lsp.type.type"] = { fg = c.red },

    -- Common plugins
    TelescopeNormal = { fg = c.fg, bg = c.bg_float },
    TelescopeBorder = { fg = c.purple, bg = c.bg_float },
    TelescopeSelection = { bg = c.bg_cursorline },
    TelescopeMatching = { fg = c.orange, bold = true },

    NvimTreeNormal = { fg = c.fg, bg = opts.transparent and "NONE" or c.bg_dark },
    NvimTreeFolderName = { fg = c.blue },
    NvimTreeOpenedFolderName = { fg = c.cyan, bold = true },

    GitSignsAdd = { fg = c.green },
    GitSignsChange = { fg = c.purple },
    GitSignsDelete = { fg = c.red },
  }
end

return M
